### ISSUE TITLE
Project infastructure setup

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-collection#13]
Basic project infastructure should be setup, allowing early access and contributing.
Following action should be performed:

- [x] setup 'yiisoft/yii2-collection' project at [packagist.org](https://packagist.org)
- [x] setup GitHub hook for 'packagist.org' package synchronization
- [x] setup project build on [Travis](https://travis-ci.org)
- [x] setup GitHub hook for 'Travis' automatic build for main branches and pull requests

**Comment by samdark** [comment]
All done.
